name: pull_request
on: [pull_request]
jobs:
  run_tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running build and test for ${{ github.ref }} branch"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Installing the project
        run: make docker/install

      - name: Running tests
        run: make docker/test